version: "3.8"

services:
  medusa-omer:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/talhazirh/talha-medusa
    container_name: medusa-talha
    networks:
      - medusa-network
    environment:
      NODE_ENV: production
      STORE_CORS: "*"
      ADMIN_CORS: "https://adminmedusa.omerzirh.com,http://localhost:9002"
      AUTH_CORS: "https://adminmedusa.omerzirh.com,http://localhost:9002"
      REDIS_URL: redis://:uOnV9g2MYYcQUHUuDyEKLcmNmOkPzqreMSz2zFjvDgWkIQUqRK8AwSxbAwppDLxD@5.161.64.194:6379
      JWT_SECRET: "super-secret"
      COOKIE_SECRET: "super-secret"
      DATABASE_URL: postgres://postgres:Omer1234@5.161.64.194:5432/medusa-medusa-store
      MEDUSA_WORKER_MODE: "shared"
    volumes:
      - medusa-uploads:/app/server/uploads
      - medusa-static:/app/server/static
    ports:
      - "9002:9002"
      - "7002:7002" 

volumes:
  medusa-uploads:
  medusa-static:

networks:
  medusa-network:
    driver: bridge